name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v3
      - name: Action Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install dependencies
        run: echo 'Ignored'
      - name: Run tests
        run: ./gradlew test